kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ template "guestbookapplication.fullname" . }}-redis-master
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: {{ template "guestbookapplication.name" . }}
      release: {{ .Release.Name }}
      role: master
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "guestbookapplication.name" . }}
        release: {{ .Release.Name }}
        role: master
        tier: backend
    spec:
      containers:
      - name: redis-master
        image: "{{ .Values.redismaster.deployment.repository }}:{{ .Values.redismaster.deployment.tag }}"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "guestbookapplication.fullname" . }}-redis-master
  labels:
    app: {{ template "guestbookapplication.name" . }}
    release: {{ .Release.Name }}
    role: master
    tier: backend
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: {{ template "guestbookapplication.name" . }}
    release: {{ .Release.Name }}
    role: master
    tier: backend
