---
apiVersion: v1
kind: Namespace
metadata:
  name: hub-helm-sub-10
---
apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  name: guestbook-subscription
  namespace: hub-helm-sub-10
# subscription is namespace-scoped resource, it is not set here to let user apply to `current` namespace
  labels:
    app: subscribed-guestbook-application
spec:
  channel: ch-helm-2/hub-local-helm-repo-2
  name: gbapp
  packageFilter:
    version: "0.1.0"
  placement:
    placementRef:
      name: guestbook-placementrule
---
apiVersion: app.ibm.com/v1alpha1
kind: PlacementRule
metadata:
  name: guestbook-placementrule
  namespace: hub-helm-sub-10
# PlacementRule is namespace-scoped resource, it is not set here to let user apply to `current` namespace
  labels:
    app: subscribed-guestbook-application
spec:
  clusterReplicas: 1
  clusterLabels:
    matchLabels:
      environment: Dev
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: subscribed-guestbook-application
  namespace: hub-helm-sub-10
# Application is namespace-scoped resource, it is not set here to let user apply to `current` namespace
spec:
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - subscribed-guestbook-application
  componentKinds:
  - group: app.ibm.com
    kind: Subscription
