---
apiVersion: v1
kind: Namespace
metadata:
  name: ch-helm
---
apiVersion: app.ibm.com/v1alpha1
kind: Channel
metadata:
  name: hub-local-helm-repo
  namespace: ch-helm
spec:
    type: HelmRepo
    pathname: https://ianzhang366.github.io/guestbook-chart/
    configRef:
      name: skip-cert-verify
---
apiVersion: v1
data:
  insecureSkipVerify: "true"
kind: ConfigMap
metadata:
  name: skip-cert-verify
  namespace: ch-helm
